Repository ansible/pylibssh, pull requests merged in 2020-08, with the labels that each got.

#119 Refactor sphinx RST parsing in towncrier extension
  docs/_ext/towncrier_draft_ext.py
  docs/changelog-fragments/119.misc.rst
Labels: bot:chronographer:provided

#121 Always rebuild changelog doc via build-docs toxenv
  tox.ini
Labels: bug, documentation

#114 Add Towncrier changelog fragments
  docs/changelog-fragments/1.feature.rst
  docs/changelog-fragments/10.feature.rst
  docs/changelog-fragments/113.bugfix.rst
  docs/changelog-fragments/119.misc.rst
  docs/changelog-fragments/14.misc.rst
  docs/changelog-fragments/15.feature.rst
  docs/changelog-fragments/25.feature.rst
  docs/changelog-fragments/26.feature.rst
  docs/changelog-fragments/27.bugfix.rst
  docs/changelog-fragments/40.feature.rst
  docs/changelog-fragments/46.bugfix.rst
  docs/changelog-fragments/58.bugfix.rst
Labels: bot:chronographer:provided, documentation, enhancement

#107 Support keyboard-authentication auth
  docs/changelog-fragments/105.feature.rst
  src/pylibsshext/includes/libssh.pxd
  src/pylibsshext/session.pyx
Labels: bot:chronographer:provided

#131 🚑 Force Sphinx to always rebuild changelog doc
  docs/_ext/towncrier_draft_ext.py
  tox.ini
Labels: bug, documentation, enhancement

#133 Produce the changelog for v0.1.0
  docs/changelog-fragments/1.breaking.rst
  docs/changelog-fragments/1.feature.rst
  docs/changelog-fragments/10.feature.rst
  docs/changelog-fragments/105.feature.rst
  docs/changelog-fragments/113.bugfix.rst
  docs/changelog-fragments/119.misc.rst
  docs/changelog-fragments/120.misc.rst
  docs/changelog-fragments/124.doc.rst
  docs/changelog-fragments/125.misc.rst
  docs/changelog-fragments/126.doc.rst
  docs/changelog-fragments/126.misc.rst
  docs/changelog-fragments/127.misc.rst
  docs/changelog-fragments/128.misc.rst
  docs/changelog-fragments/14.misc.rst
  docs/changelog-fragments/15.feature.rst
  docs/changelog-fragments/25.feature.rst
  docs/changelog-fragments/26.feature.rst
  docs/changelog-fragments/27.bugfix.rst
  docs/changelog-fragments/40.feature.rst
  docs/changelog-fragments/46.bugfix.rst
  docs/changelog-fragments/58.bugfix.rst
  docs/changelog-fragments/72.misc.rst
  docs/changelog.rst
Labels: enhancement

#141 Add initial user guide doc
  .pre-commit-config.yaml
  docs/_samples/copy_files.py
  docs/_samples/get_version.py
  docs/changelog-fragments/141.doc.rst
  docs/index.rst
  docs/user_guide.rst
Labels: bot:chronographer:provided, documentation, enhancement
