Repository ansible/pylibssh, pull requests merged in 2021-02, with the labels that each got.

#170 Adjust the `get-pip.py` URL in CI for Python 3.5
  .github/workflows/build-test-n-publish.yml
Labels: bug

#171 Adjust the source per improved checks in wemake-python-styleguide v0.15
  docs/conf.py
  src/pylibsshext/_compat.py
Labels: enhancement

#172 Reintroduce flake8-erradicate
  .flake8
  .pre-commit-config.yaml
Labels: enhancement

#168 Check for SSH_ERROR on channel_read_nonblocking
  docs/changelog-fragments/168.bugfix.rst
  src/pylibsshext/channel.pyx
  src/pylibsshext/errors.pyx
Labels: bot:chronographer:provided

#178 Merge-in a part of Git subtree from pyca/infra
  .github/dependabot.yml
  .github/workflows/build-docker-images.yml
  .github/workflows/build-test-n-publish.yml
  build-scripts/manylinux-container-image/Dockerfile
  build-scripts/manylinux-container-image/LICENSE.APACHE
  build-scripts/manylinux-container-image/LICENSE.BSD
  build-scripts/manylinux-container-image/README.md
  build-scripts/manylinux-container-image/install_libffi.sh
  build-scripts/manylinux-container-image/install_openssl.sh
  build-scripts/manylinux-container-image/install_perl.sh
  build-scripts/manylinux-container-image/install_virtualenv.sh
  build-scripts/manylinux-container-image/openssl-version.sh
  tox.ini
Labels: bug, enhancement
