Repository ansible/pylibssh, pull requests merged in 2022-09, with the labels that each got.

#343 Support specifying socket fd for connection.
  docs/changelog-fragments/343.feature.rst
  src/pylibsshext/session.pyx
Labels: bot:chronographer:provided

#368 Regenerate pip constraints for docs w/ pip-compile
  docs/requirements.txt
Labels: documentation, dependencies, bot:chronographer:skip

#370 Tell pre-commit.ci to send update PRs quarterly
  .pre-commit-config.yaml
Labels: dependencies, bot:chronographer:skip

#371 Integrate pygrep in pre-commit
  .pre-commit-config.yaml
  docs/changelog.rst
  docs/index.rst
Labels: bot:chronographer:skip

#373 Prevent flake8 pre-commit hook version updates
  .pre-commit-config.yaml
Labels: dependencies, bot:chronographer:skip

#374 Split flake8 pre-commit hook into 2 by WPS plugin
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#377 Drop py2 compatibility code from PEP 517 backend
  bin/pep517_backend/_backend.py
  bin/pep517_backend/_compat.py
  bin/pep517_backend/_transformers.py
  bin/pep517_backend/hooks.py
  docs/changelog-fragments/377.misc.rst
  pyproject.toml
Labels: enhancement, bot:chronographer:provided, python

#379 Add Fedora 37 to the GHA CI workflow
  .github/workflows/build-test-n-publish.yml
Labels: bot:chronographer:skip

#378 Fix cutting off expandvars from RPM spec @ Fedora
  docs/changelog-fragments/378.misc.rst
  packaging/rpm/ansible-pylibssh.spec
Labels: bug, bot:chronographer:provided, dependencies

#380 Add UBI 9 to the GHA CI matrix
  .github/workflows/build-test-n-publish.yml
Labels: github_actions, bot:chronographer:skip

#381 Replace deprecated Ubuntu 18.04 VM with 20.04 @ GHA
  .github/workflows/build-test-n-publish.yml
  docs/changelog-fragments/379.deprecation.rst
Labels: enhancement, bot:chronographer:provided, github_actions

#382 Replace RPM `%{expr}` with GHA expressions syntax
  .github/workflows/build-test-n-publish.yml
Labels: bug, github_actions, bot:chronographer:skip

#383 Upgrade pypa/gh-action-pypi-publish to release/v1
  .github/workflows/build-test-n-publish.yml
Labels: github_actions, bot:chronographer:skip

#227 Add an initial Packit configuration
  .packit.yml
  docs/changelog-fragments/227.misc.rst
  docs/changelog-fragments/246.misc.rst
  packaging/rpm/ansible-pylibssh.spec
Labels: enhancement, bot:chronographer:provided

#386 Integrate yamllint
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/codecov.yml
  .github/config.yml
  .github/dependabot.yml
  .github/workflows/build-manylinux-container-images.yml
  .github/workflows/build-test-n-publish.yml
  .github/workflows/tox-linters.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  .yamllint
Labels: bot:chronographer:skip
