Repository ansible/pylibssh, pull requests merged in 2022-07, with the labels that each got.

#331 Add the ability to override the password prompt in keyboard-interactive
  docs/changelog-fragments/331.feature.rst
  src/pylibsshext/session.pyx
Labels: bot:chronographer:provided

#350 Integrate PEP 517 build constraints into tox
  requirements-build.in
  requirements-build.txt
  tox.ini
Labels: enhancement

#352 Use absolute paths in the RPM spec's `PYTHONPATH`
  packaging/rpm/ansible-pylibssh.spec
Labels: bug, dependencies, bot:chronographer:skip

#353 ⇪Bump setuptools-scm-git-archive to v1.4 @ RPM
  packaging/rpm/ansible-pylibssh.spec
Labels: dependencies, bot:chronographer:skip

#354 Unduplicate pyparsing dep in RPM spec
  packaging/rpm/ansible-pylibssh.spec
Labels: dependencies, bot:chronographer:skip

#355 Replace F34 with F35 and F36 in GHA
  .github/workflows/build-test-n-publish.yml
Labels: enhancement, bot:chronographer:skip

#356 Stop allowing errors in UBI RPM builds @ GHA
  .github/workflows/build-test-n-publish.yml
Labels: bot:chronographer:skip

#357 Add UBI v8.6 to the CI matrix
  .github/workflows/build-test-n-publish.yml
Labels: bot:chronographer:skip
