Repository ansible/pylibssh, pull requests merged in 2023-11, with the labels that each got.

#533 Add manylinux_2_28 support
  .github/workflows/build-manylinux-container-images.yml
  .github/workflows/ci-cd.yml
  build-scripts/manylinux-container-image/Dockerfile
  build-scripts/manylinux-container-image/update-packages.sh
  docs/changelog-fragments/533.misc.rst
  requirements-build.txt
Labels: bot:chronographer:provided

#532 Start building Python 3.12 wheels
  .github/workflows/ci-cd.yml
  docs/changelog-fragments/532.misc.rst
  requirements-build.txt
  setup.cfg
  tox.ini
Labels: bot:chronographer:provided

#527 Support changing SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES
  docs/changelog-fragments/527.feature.rst
  src/pylibsshext/session.pyx
Labels: bot:chronographer:provided

#535 This should be called out as a feature
  docs/changelog-fragments/532.feature.rst
Labels: bot:chronographer:skip

#539 📝 Add `contrib` & `packaging` change note types
  .pre-commit-config.yaml
  docs/changelog-fragments/.gitignore
  docs/changelog-fragments/539.contrib.rst
  docs/changelog-fragments/README.rst
  pyproject.toml
Labels: documentation, bot:chronographer:provided

#538 🧪🐛 Make coverage use upstream Cython plugin
  .coveragerc
  bin/cython_coverage.py
  docs/changelog-fragments/538.contrib.rst
  tox.ini
Labels: bot:chronographer:provided, dependencies

#501 🎨 Migrate PEP 517 backend to `tomllib`+`tomli`
  docs/changelog-fragments/501.packaging.rst
  packaging/pep517_backend/_backend.py
  packaging/pep517_backend/_compat.py
  pyproject.toml
Labels: bot:chronographer:provided

#540 📦 Demand Cython 3 under Python 3.12+
  docs/changelog-fragments/502.packaging.rst
  pyproject.toml
Labels: bot:chronographer:provided, dependencies

#541 📦🐛 Fix PEP 660 editable install mode
  .flake8
  docs/changelog-fragments/541.contrib.rst
  docs/changelog-fragments/541.packaging.rst
  packaging/pep517_backend/_backend.py
  packaging/pep517_backend/hooks.py
Labels: enhancement, bot:chronographer:provided, dependencies
