Repository ansible/pylibssh, pull requests merged in 2024-01, with the labels that each got.

#553 📝💅 Use tox to build docs on RTD
  .readthedocs.yaml
  tox.ini
Labels: documentation, bot:chronographer:skip

#554 🧪 Turn warnings into errors in docs build envs
  .readthedocs.yaml
  tox.ini
Labels: documentation, bot:chronographer:skip

#502 🎨Only use setuptools-scm-git-archive under < py37
  .github/workflows/ci-cd.yml
  docs/changelog-fragments/502.packaging.rst
  pyproject.toml
  requirements-build.txt
Labels: bot:chronographer:provided

#474 Spell "Connect" @ `Session.connect()` docstring
  docs/changelog-fragments/474.contrib.rst
  docs/changelog-fragments/474.doc.rst
  src/pylibsshext/session.pyx
Labels: bot:chronographer:provided

#559 🧪 Separate manylinux wheels building workflow
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
  docs/changelog-fragments/559.contrib.rst
Labels: enhancement, github_actions, bot:chronographer:skip

#560 🧪 Separate the testing workflow
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-tests.yml
  docs/changelog-fragments/560.contrib.rst
Labels: enhancement, github_actions, bot:chronographer:skip

#561 🧪📦 Build macOS wheels with `cibuildwheel`
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-cibuildwheel.yml
  docs/changelog-fragments/333.contrib.rst
  docs/changelog-fragments/333.packaging.rst
  pyproject.toml
Labels: enhancement, bot:chronographer:provided, github_actions

#565 Fix the workflow location in the release doc
  docs/changelog-fragments/565.contrib.rst
  docs/contributing/release_guide.rst
Labels: bot:chronographer:provided
