Repository ansible/pylibssh, pull requests merged in 2024-06, with the labels that each got.

#601 ⇪ Bump the `setuptools-scm` pin to v8.1.0
  docs/changelog-fragments/601.contrib.rst
  docs/changelog-fragments/601.packaging.rst
  requirements-build.txt
Labels: bot:chronographer:provided, dependencies

#615 📦 Run import checks during RPM creation
  docs/changelog-fragments/615.packaging.rst
  packaging/rpm/ansible-pylibssh.spec
Labels: bot:chronographer:provided

#621 Fix reading large files over SCP
  docs/changelog-fragments/621.bugfix.rst
  src/pylibsshext/scp.pyx
  tests/unit/scp_test.py
Labels: bug, bot:chronographer:provided
