Repository ansible/pylibssh, pull requests merged in 2025-03, with the labels that each got.

#676 🧪 Bump `actions/{upload,download}-artifact` to v4
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
  .github/workflows/reusable-cibuildwheel.yml
  .github/workflows/reusable-tests.yml
  docs/changelog-fragments/676.contrib.rst
Labels: bot:chronographer:provided, github_actions

#562 Build Linux platform wheels with `cibuildwheel`
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
  .github/workflows/reusable-cibuildwheel.yml
  build-scripts/build-all-manylinux-wheels.sh
  build-scripts/build-manylinux-wheels.sh
  docs/changelog-fragments/562.breaking.rst
  docs/changelog-fragments/562.contrib.rst
  docs/changelog-fragments/562.packaging.rst
  docs/installation_guide.rst
  pyproject.toml
  tox.ini
Labels: enhancement, bot:chronographer:provided, github_actions

#683 📦 Bump `cibuildwheel` to v2.17.0
  .github/workflows/reusable-cibuildwheel.yml
Labels: dependencies

#681 📦 Bump Cython to v3.0.12
  requirements-build.txt
Labels: dependencies

#682 📦 Integrate `PIP_CONSTRAINT` @ `cibuildwheel`
  pyproject.toml
  requirements-build.txt
Labels: dependencies

#675 Add support for specifying Kex Algos
  docs/changelog-fragments/675.feature.rst
  src/pylibsshext/session.pyx
Labels: bot:chronographer:provided

#638 Fix large SFTP reads
  docs/changelog-fragments/638.bugfix.rst
  src/pylibsshext/sftp.pyx
  tests/unit/sftp_test.py
Labels: bot:chronographer:provided

#688 🧪 Test pre-built dists via tox's `--installpkg`
  .github/workflows/reusable-tests.yml
  docs/changelog-fragments/688.contrib.rst
  docs/conf.py
  tox.ini
Labels: bot:chronographer:provided

#692 🐛📦 Fix the OCI manylinux image platform tag
  .github/workflows/build-manylinux-container-images.yml
  docs/changelog-fragments/692.contrib.rst
  docs/changelog-fragments/692.packaging.rst
Labels: bug, bot:chronographer:provided, github_actions

#664 Increase SFTP chunk size to increase the SFTP throughput in both directions
  docs/changelog-fragments/664.bugfix.rst
  src/pylibsshext/includes/libssh.pxd
  src/pylibsshext/includes/sftp.pxd
  src/pylibsshext/sftp.pyx
  tests/unit/sftp_test.py
Labels: bot:chronographer:provided

#658 Prevent `SEGFAULT`s on consecutive `exec_command()` invocations
  .github/workflows/ci-cd.yml
  docs/changelog-fragments/658.bugfix.rst
  docs/changelog-fragments/658.packaging.rst
  packaging/rpm/ansible-pylibssh.spec
  pytest.ini
  src/pylibsshext/channel.pxd
  src/pylibsshext/channel.pyx
  src/pylibsshext/session.pxd
  src/pylibsshext/session.pyx
  tests/conftest.py
  tests/unit/channel_test.py
  tox.ini
Labels: bot:chronographer:provided
